name: 'Release'
description: 'Releases a package'
inputs:
  scope:
    description: 'The package to release. Must match a package specified in lerna.json.'
  tag:
    description: 'The tag to publish to on NPM (DRY RUN).'
  preid:
    description: 'The prerelease identifier used when doing a prerelease.'
  working-directory:
    required: true
    description: 'The directory of the package to deploy.'
  node-version:
    description: 'Node.js version to use for publishing.'
    required: false
    default: '20.10.0'
  registry-url:
    description: 'Registry URL to publish to.'
    required: false
    default: 'https://registry.npmjs.org'
runs:
  using: 'composite'
  steps:
    - name: ğŸ“¦ Install pnpm
      uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
    - name: ğŸŸ¢ Use Node
      uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        registry-url: ${{ inputs.registry-url }}
    - name: ğŸ”„ Ensure Latest npm
      run: npm install -g npm@latest
      shell: bash
    - name: Install Dependencies
      run: pnpm --filter ${{ inputs.scope }} install
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: ğŸ—ï¸ Run Build
      run: pnpm run build
      shell: bash
      working-directory: ${{ inputs.working-directory }}
    - name: ğŸ“¦ Publish to NPM
      run: |
        if [ -n "${{ inputs.preid }}" ]; then
          npm publish --tag ${{ inputs.tag }} --preid ${{ inputs.preid }} --provenance
        else
          npm publish --tag ${{ inputs.tag }} --provenance
        fi
      shell: bash
      working-directory: ${{ inputs.working-directory }}
