name: Build & Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: ğŸŸ¢ Use Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: ğŸ”§ Install Dependencies
        run: pnpm install

      - name: ğŸ—ï¸ Build
        run: pnpm run build

      - name: ğŸ” Check Git Context
        uses: ./.github/workflows/actions/check-git-context

      - name: ğŸ“¤ Upload Build Artifacts
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: build-artifacts
          path: |
            packages/*/dist
            packages/*/loader
            example-project/component-library/dist
            example-project/component-library/loader
            example-project/component-library-angular
            example-project/component-library-react/dist
            example-project/component-library-vue/dist
          retention-days: 1

  test:
    name: Test ${{ matrix.ecosystem }} (${{ matrix.os }})
    needs: build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: ['macos-latest', 'windows-latest']
        ecosystem: ['angular', 'react', 'vue', 'ssr']
        include:
          - ecosystem: angular
            filter: --filter "@stencil/angular-output-target" --filter "*angular*" --filter "ng-app"
          - ecosystem: react
            filter: --filter "@stencil/react-output-target" --filter "*react*" --filter "remix-app"
          - ecosystem: vue
            filter: --filter "@stencil/vue-output-target" --filter "*vue*" --filter "*nuxt*"
          - ecosystem: ssr
            filter: --filter "@stencil/ssr" --filter "next-app"
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: ğŸŸ¢ Use Node
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version-file: .nvmrc
          cache: 'pnpm'

      - name: ğŸ”§ Install Dependencies
        run: pnpm install

      - name: ğŸ“¥ Download Build Artifacts
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: build-artifacts
          path: .

      - name: ğŸ§ª Test
        run: pnpm ${{ matrix.filter }} test

  format:
    name: Format
    uses: ./.github/workflows/format.yml

