name: CI

on:
  pull_request:
  push:

jobs:
  build-output-targets:
    name: Build output-targets
    runs-on: ubuntu-latest
    steps:

      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0

      - name: ğŸŸ¢ Use Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
          cache: 'pnpm'
      - name: ğŸ•¸ï¸ Install
        run: pnpm i --frozen-lockfile
      - name: ğŸ—ï¸ Build packages
        run: pnpm build.angular && pnpm build.react && pnpm build.vue

  test-angular-example:
    name: Angular example tests (Jest)
    runs-on: ubuntu-latest
    needs: build-output-targets
    steps:
      - name: ğŸ“¥ Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: ğŸ“¦ Setup pnpm
        uses: pnpm/action-setup@v4

      - name: ğŸŸ¢ Use Node
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 20
          cache: 'pnpm'
      - name: ğŸ•¸ï¸ Install
        run: pnpm i --frozen-lockfile
      - name: ğŸ—ï¸ Build packages (needed by example projects)
        run: pnpm build.angular && pnpm build.react && pnpm build.vue
      - name: ğŸ—ï¸ Build component-library
        run: pnpm build.example.core
      - name: ğŸ§ª Run Angular example tests
        run: pnpm --filter component-library-angular test
