name: Needs Reproduction

on:
  issues:
    types: [labeled]

permissions:
  issues: write

jobs:
  reproduire:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'needs reproduction'
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4
      - uses: Hebilicious/reproduire@v0.0.9
        with:
          label: needs reproduction
